## URLS
# EX.: path(url, view, name)
# A url É A ROTA QUE DEVE SER REQUISITADA PARA ACESSAR O METODO 

## VIEWS
# TODA VIEW DEVE RECEBER UMA REQUEST COMO PARAMETRO 
# E RETORNAR UMA UMA RESPOSTA, GERALMENTE ('HttpResponse')

## MODELS :
# ARQUIVO DE ESTRUTURAÇÃO/AÇÕES QUE INTERLIGARÁ 
# A APLICAÇÃO COM O BANCO DE DADOS

## MIGRATIONS :
# RESPONSAVEL PELA TRANSFERENCIA DOS COMANDOS DA MODEL
# PARA INSTRUÇÕES AO BANCO DE DADOS, CRIANDO/PREENCHENDO
# AS TRABELAS.
